apiVersion: v1
kind: Service
metadata:
  name: ftms-backend-service
  namespace: ftms
  labels:
    app: ftms-backend
spec:
  type: LoadBalancer
  selector:
    app: ftms-backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080